language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=./
    - PLATFORMIO_EXTRA_SCRIPTS=platformio_script.py

install:
    - pip install -U platformio

script:
    - cd airrohr-firmware && platformio ci --verbose --project-conf=platformio.ini && ls -l builds/
